[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token22_swap = "H8j9y1sARxb73rL2RFqfpKG8Yi9CYXmgcha5n7QLYmbU"
whitelist_hook = "EYzLSaUydn5GLBov2G1ypmL7s3zYqNyNfxY3BQZ7Rdy2"

[programs.devnet]
token22_swap = "H8j9y1sARxb73rL2RFqfpKG8Yi9CYXmgcha5n7QLYmbU"
whitelist_hook = "EYzLSaUydn5GLBov2G1ypmL7s3zYqNyNfxY3BQZ7Rdy2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\ADMIN\\.config\\solana\\id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"